// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppIconButton: typeof import('./src/components/app/IconButton.vue')['default']
    AppSlider: typeof import('./src/components/app/Slider.vue')['default']
    TheControls: typeof import('./src/components/TheControls.vue')['default']
    TheDrawer: typeof import('./src/components/TheDrawer.vue')['default']
    TheToolSwitch: typeof import('./src/components/TheToolSwitch.vue')['default']
    TheUniverse: typeof import('./src/components/TheUniverse.vue')['default']
  }
}

export { }
