// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/app/Button.vue')['default']
    AppIconButton: typeof import('./src/components/app/IconButton.vue')['default']
    AppSlider: typeof import('./src/components/app/Slider.vue')['default']
    IFaRegularSquare: typeof import('virtual:vite-icons/fa-regular/square')['default']
    IFaSolidEllipsisH: typeof import('virtual:vite-icons/fa-solid/ellipsis-h')['default']
    IFaSolidPause: typeof import('virtual:vite-icons/fa-solid/pause')['default']
    IFaSolidPlay: typeof import('virtual:vite-icons/fa-solid/play')['default']
    IFaSolidSquare: typeof import('virtual:vite-icons/fa-solid/square')['default']
    IFaSolidUndoAlt: typeof import('virtual:vite-icons/fa-solid/undo-alt')['default']
    TheConfiguration: typeof import('./src/components/TheConfiguration.vue')['default']
    TheControls: typeof import('./src/components/TheControls.vue')['default']
    TheReloadPrompt: typeof import('./src/components/TheReloadPrompt.vue')['default']
    TheToolToggle: typeof import('./src/components/TheToolToggle.vue')['default']
    TheUniverse: typeof import('./src/components/TheUniverse.vue')['default']
  }
}

export { }
