[package]
name = "universe"
version = "0.1.0"
authors = ["Jason Theiler <turret.jason@outlook.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"
web-sys = { version = "0.3.50", features = ["console"] }

[profile.release]
opt-level = "s"
